import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, year2023, year2024 }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="grow flex gap-4 min-h-screen  p-8">
          {children}
          <div className="grow bg-white p-4 rounded-xl">
            {year2023}
            <hr className="h-px my-4 bg-gray-200 border-0 dark:bg-gray-700" />
            {year2024}
          </div>
        </main>
      </body>
    </html>
  );
}
